version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      EUREKA_URL: http://localhost:8761/eureka
      APP_NAME: nova-os-infinitec
  db:
    restart: always
    image: postgres:9.6.9
    environment:
      POSTGRES_DB: infinitec
      POSTGRES_USER: infinitec
      POSTGRES_PASS: infinitec
    ports:
      - 5432:5432
